# Makefile for P1 project

CC = gcc
CFLAGS = -Wall -ansi -pedantic
TARGET = Entry
DEP_1 = Utility
DEP_2 = Get_Data
DEP_3 = $(User_Dialogue/User_Dialogue)
DEP_4 = $(Simulate_House/White_Goods)

$(TARGET).exe: $(TARGET).c $(DEP_1).o $(DEP_2).o $(DEP_3).o $(DEP_4).o
	$(CC) $(CFLAGS) $(TARGET).c -o $(TARGET).exe
	
$(DEP_1).o: $(DEP_1).c $(DEP_1).h
	$(CC) -c $(DEP_1).c
	
$(DEP_2).o: $(DEP_2).c $(DEP_2).h $(DEP_1).h
	$(CC) -c $(DEP_2).c
	
$(DEP_3).o: $(DEP_3).c $(DEP_3).h $(DEP_4).h $(DEP_2).h $(DEP_1).h
	$(CC) -c $(DEP_3).c
	
$(DEP_4).o: $(DEP_4).c $(DEP_4).h
	$(CC) -c $(DEP_4).c

clean:
	rm *.o $(TARGET).exe *~ *.swp