# Makefile for P1 project

CC = gcc
CFLAGS = -Wall -ansi -pedantic
TARGET = Entry
DEPS = Utility.h Get_Data.h White_Goods.h User_Dialogue.h Analyze_Data.h
OBJ  = Utility.c Get_Data.c White_Goods.c User_Dialogue.c Analyze_Data.c Entry.c


%.o: %.c $(DEPS)
	$(CC) -o -c $@ $< $(CFLAGS)

$(TARGET).exe: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)

clean:
	rm *.o $(TARGET).exe *~ *.swp