# Makefile for P1 project

CC = gcc
CFLAGS = -Wall -ansi -pedantic
TARGET = Entry
DEP_1 = Utility
DEP_2 = Get_Data
DEP_3 = White_Goods
DEP_4 = Analyze_Data
DEP_5 = User_Dialogue

$(TARGET).exe: $(DEP_5).o $(TARGET).c
	$(CC) $(CFLAGS) $(TARGET).c -o $(TARGET).exe
	
$(DEP_1).o: $(DEP_1).c $(DEP_1).h
	$(CC) -c $(DEP_1).c
	
$(DEP_2).o: $(DEP_2).c $(DEP_2).h
	$(CC) -c $(DEP_2).c
	
$(DEP_3).o: $(DEP_3).c $(DEP_3).h
	$(CC) -c $(DEP_3).c
	
$(DEP_4).o: $(DEP_4).c $(DEP_4).h
	$(CC) -c $(DEP_4).c

$(DEP_5).o: $(DEP_5).c $(DEP_5).h $(DEP_1).o $(DEP_2).o $(DEP_3).o $(DEP_4).o
	$(CC) -c $(DEP_5).c


clean:
	rm *.o $(TARGET).exe *~ *.swp